### PR TITLE
Updated azurerm_storage_account names to be unique

### PR DESCRIPTION
**Pull request by BradySkylight**

### CODE REVIEW

**Review by DanPaseltiner — CHANGES_REQUESTED** [review]
This is great, but I would like us to use something other than just Subscription ID to make these names be unique across all of Azure. As I mentioned in slack, using subscription ID here will not allow one user to have multiple separate deployments of the Starter Kit. I don't know why they would want to do this instead of just adding a new environment to a single deployment, but it seems easy enough for us allow for this possibility by combining subscription ID with resource group name or simply using a unix timestamp. Thoughts?

**Comment by BradySkylight** [comment]
> This is great, but I would like us to use something other than just Subscription ID to make these names be unique across all of Azure. As I mentioned in slack, using subscription ID here will not allow one user to have multiple separate deployments of the Starter Kit. I don't know why they would want to do this instead of just adding a new environment to a single deployment, but it seems easy enough for us allow for this possibility by combining subscription ID with resource group name or simply using a unix timestamp. Thoughts?

This makes a lot of sense, and we are already doing this in other cases.  I think it makes more sense to use both the Subscription ID as well as the Resource Group Name as it has more meaning.  I'll update the code.

**Comment by BradySkylight** [comment]
> > This is great, but I would like us to use something other than just Subscription ID to make these names be unique across all of Azure. As I mentioned in slack, using subscription ID here will not allow one user to have multiple separate deployments of the Starter Kit. I don't know why they would want to do this instead of just adding a new environment to a single deployment, but it seems easy enough for us allow for this possibility by combining subscription ID with resource group name or simply using a unix timestamp. Thoughts?
> 
> This makes a lot of sense, and we are already doing this in other cases. I think it makes more sense to use both the Subscription ID as well as the Resource Group Name as it has more meaning. I'll update the code.

After further discussion, moving forward with unix timestamp to make it unique.

**Review by nickclyde — APPROVED** [review]
Looks good!

**Review by DanPaseltiner — APPROVED** [review]
Awesome!

**Pull request merged**
