### PR TITLE
Add deployment of phdi-tabulate container app

### PR DESCRIPTION
**Pull request by nickclyde**
Resolves https://app.clickup.com/t/32ytjky

### CODE REVIEW

**Review by gordonfarrell — APPROVED** [review]
LGTM!

**Review by DanPaseltiner — COMMENTED** [review]
Is the intent to handle mounting a storage volume in a separate PR? Totally fine by me if that's the case.

**Comment by nickclyde** [comment]
@DanPaseltiner Yeah that was what I was thinking, since I still need to do a bit more digging into the docs to see how it works.

**Comment by DanPaseltiner** [comment]
@nickclyde makes perfect sense to me!

**Pull request merged**
